name: Create Changelog and Release from Integration

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha

jobs:

  create-changelog-and-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
        with:
          # we need this, to circumflex eh -vent branch protection
          token: ${{ secrets.AUTH_TOKEN }}
      - name: Prepare repository
        run: git fetch --unshallow --tags
      # create actual release and thus commits on release
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install pnpm
        run: npm i -g pnpm
      - name: bootstrap monorepo
        run: pnpm i -r
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: pnpm run publish-all
      # push release branch
      - name: push release branch with new tags
        run: git push origin ${GITHUB_REF##*/} --follow-tags
      # now merge release branch into develop and push develop
      - name: checkout develop
        run: git checkout develop
      - name: update develop
        run: git pull origin develop
      - name: merge release branch into develop
        run: git merge ${GITHUB_REF##*/}
      - name: push develop
        run: git push origin develop

